import type { Metadata } from "next";
import { Ubuntu, Ubuntu_Mono } from "next/font/google";
import Navbar from "./components/navbar/page";
import "./globals.css";

const ubuntuSans = Ubuntu({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ubuntuSans.variable} ${ubuntuMono.variable} h-full antialiased`}
    >
      <body className="bg-slate-100 text-slate-800 min-h-screen dark:bg-slate-950 dark:text-slate-100">
        <Navbar />
        <div className="min-h-screen bg-slate-100">{children}</div>
      </body>
    </html>
  );
}
